<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType> <!-- Suppresses the background console terminal -->
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);NU1605;NU1510</NoWarn>

    <!-- True Single-File Self-Contained Settings -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="base\lothin.zip" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="s_assets\**" />

    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.13" />
    <PackageReference Include="Avalonia" Version="11.0.13" />
    <PackageReference Include="Avalonia.Desktop" Version="11.0.13" />
    <PackageReference Include="Clippit" Version="3.4.6" />
    <PackageReference Include="Docnet.Core" Version="2.6.0" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.14.0" />
    <PackageReference Include="PdfSharp" Version="6.1.1" />
  </ItemGroup>

</Project>